version: "3"

services:
  app:
    image: simplycodedsoftware/php:8.1
    volumes:
      - "$PWD:/data/app"
    working_dir: "/data/app"
    container_name: "ecotone_playground"
    command: sleep 99999
    networks:
      - default
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      COMPOSER_HOME: /data/app
      COMPOSE_HTTP_TIMEOUT: 9999
      DATABASE_DSN: pgsql://ecotone:secret@database:5432/ecotone
  database:
    image: postgres:12.1
    networks:
      - default
    environment:
      POSTGRES_USER: "card"
      POSTGRES_PASSWORD: "secret"
    ports:
      - "5432:5432"
networks:
  default:
    external:
      name: ecotone-test